### ISSUE TITLE
inkonsistency panic

### ISSUE THREAD

**Issue by jxsl13** [jxsl13/goripr#18]
```
panic: reasons inconsistent

goroutine 114 [running]:
github.com/jxsl13/goripr/v2.(*Client).Find(0xc0005a9140, {0xa4e9a8, 0xc0003cd540}, {0xc000012e00?, 0xa4e7e8?})
        github.com/jxsl13/goripr/v2@v2.0.1/redis.go:670 +0x674
github.com/jxsl13/TeeworldsEconVPNDetectionGo/vpn.(*VPNChecker).foundInCache(0xc000054d34?, {0xc000012e00?, 0xc0000f4a5d?})
        github.com/jxsl13/TeeworldsEconVPNDetectionGo/vpn/checker.go:49 +0x36
github.com/jxsl13/TeeworldsEconVPNDetectionGo/vpn.(*VPNChecker).IsVPN(0xc0003ccd40, {0xc0000f4a5d?, 0x0?})
        github.com/jxsl13/TeeworldsEconVPNDetectionGo/vpn/checker.go:105 +0xf3
github.com/jxsl13/TeeworldsEconVPNDetectionGo/econ.vpnCheck(0xc000036120, {0xc0000f4a5d, 0xc}, 0xc000054fd0?, 0x4e94914f0000, {0xc00002c6a0, 0x1a})
        github.com/jxsl13/TeeworldsEconVPNDetectionGo/econ/econ.go:33 +0x55
created by github.com/jxsl13/TeeworldsEconVPNDetectionGo/econ.NewEvaluationRoutine in goroutine 65
        github.com/jxsl13/TeeworldsEconVPNDetectionGo/econ/econ.go:110 +0x711
```

**Comment by jxsl13** [comment]
smost likely  due to Redis db version (5.0.7) mismatch
