### ISSUE TITLE
[under review]Some logic error

### ISSUE THREAD

**Issue by jxsl13** [jxsl13/goripr#5]
```
2021/01/30 21:35:36 [NO VPN]: xxxxxxxx
2021/01/30 21:38:32 Subscriber pushed message into channel
panic: runtime error: index out of range [0] with length 0

goroutine 50 [running]:
github.com/jxsl13/goripr.(*Client).Find(0xc0000f8960, 0xc0003281a0, 0xd, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/jxsl13/goripr@v1.1.0/redis.go:721 +0x5f8
main.processMessage(0xc0000162e0, 0x11, 0xc0000ea0b0, 0xaf, 0xc0000f8960, 0xc00004d680, 0x99bb00, 0x0, 0x0)
	/build/process_message.go:22 +0x31a
main.main.func1()
	/build/main.go:76 +0xe8
created by main.main
	/build/main.go:74 +0xa5
```

https://github.com/jxsl13/goripr/blob/6d3f55d06f953cfe3afad826e4cd772443096a3c/redis.go#L721

**Comment by jxsl13** [comment]
seemingly the database has become inconsistent (running in a docker container).
Somehow all of the keys were dumped and weird other keys were added.

**Comment by jxsl13** [comment]
Don't run it unknowingly exposed to the internet.
